sql sql-lms-mac {
    driver = "rlm_sql_postgresql"
    dialect = "postgresql"
    server = "db"
    port = 5432
    login = "lms"
    password = "lmspassword"
    radius_db = "lms"

    sql_user_name = "%{User-Name}"

    authorize_check_query = "SELECT id, upper(mac) AS UserName, 'Cleartext-Password' AS Attribute, '' AS Value, ':=' AS op \
        FROM nodes \
        WHERE upper(mac) = upper('%{SQL-User-Name}') AND access = 1 ORDER BY id"
}
