sql sql-lms-lastonline {
    driver = "rlm_sql_postgresql"
    dialect = "postgresql"
    server = "db"
    port = 5432
    login = "lms"
    password = "lmspassword"
    radius_db = "lms"

    sql_user_name = "%{User-Name}"

    postauth_query = "UPDATE nodes SET lastonline = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP(0))::integer WHERE lower(name) = lower('%{User-Name}')"
}
