sql sql-lms-pppoe {
    driver = "rlm_sql_postgresql"
    dialect = "postgresql"
    server = "db"
    port = 5432
    login = "lms"
    password = "lmspassword"
    radius_db = "lms"

    sql_user_name = "%{User-Name}"

    authorize_check_query = "SELECT \
        id, lower(name) AS UserName, 'Cleartext-Password' AS Attribute, passwd AS Value, ':=' AS op \
        FROM vnodes \
        WHERE lower(name) = lower('%{User-Name}') \
        UNION \
        SELECT id, lower(name) AS UserName, 'Simultaneous-Use' AS Attribute, '1' AS Value, ':=' AS op \
        FROM vnodes \
        WHERE lower(name) = lower('%{User-Name}')"

    authorize_reply_query = "SELECT \
        id, lower(name) AS UserName, 'Framed-IP-Address' AS Attribute, inet_ntoa(ipaddr) AS Value, ':=' AS op \
        FROM vnodes \
        WHERE lower(name) = lower('%{User-Name}') \
        UNION \
        SELECT 0 AS id, '%{User-Name}' AS UserName, 'Mikrotik-Rate-Limit' AS Attribute, \
            (ROUND(COALESCE(x.upceil, y.upceil, z.upceil)) || 'k' || '/' || ROUND(COALESCE(x.downceil, y.downceil, z.downceil)) || 'k') AS Value, ':=' AS op \
        FROM ( \
            SELECT n.id, MIN(n.name) AS name, SUM(t.downceil/o.cnt) AS downceil, SUM(t.upceil/o.cnt) AS upceil \
            FROM nodeassignments na \
            JOIN assignments a ON (na.assignmentid = a.id) \
            JOIN tariffs t ON (a.tariffid = t.id) \
            JOIN vnodes n ON (na.nodeid = n.id) \
            JOIN ( \
                SELECT assignmentid, COUNT(*) AS cnt \
                FROM nodeassignments \
                GROUP BY assignmentid \
            ) o ON (o.assignmentid = na.assignmentid) \
            WHERE a.datefrom <= EXTRACT(EPOCH FROM CURRENT_TIMESTAMP(0))::integer \
                AND (a.dateto > EXTRACT(EPOCH FROM CURRENT_TIMESTAMP(0))::integer OR a.dateto = 0) \
                AND a.suspended = 0 AND lower(n.name) = lower('%{User-Name}') \
            GROUP BY n.id \
        ) x \
        LEFT JOIN ( \
            SELECT SUM(t.downceil/o.cnt) AS downceil, SUM(t.upceil/o.cnt) AS upceil \
            FROM assignments a \
            JOIN tariffs t ON (a.tariffid = t.id) \
            JOIN vnodes n ON (a.customerid = n.ownerid) \
            JOIN ( \
                SELECT COUNT(*) AS cnt, ownerid FROM vnodes \
                WHERE NOT EXISTS ( \
                    SELECT 1 FROM nodeassignments, assignments a \
                    WHERE assignmentid = a.id AND nodeid = vnodes.id \
                        AND a.suspended = 0 AND (a.dateto > EXTRACT(EPOCH FROM CURRENT_TIMESTAMP(0))::integer OR a.dateto = 0)) \
                GROUP BY ownerid \
            ) o ON (o.ownerid = n.ownerid) \
            WHERE a.datefrom <= EXTRACT(EPOCH FROM CURRENT_TIMESTAMP(0))::integer \
                AND (a.dateto > EXTRACT(EPOCH FROM CURRENT_TIMESTAMP(0))::integer OR a.dateto = 0) AND a.suspended = 0 \
                AND NOT EXISTS (SELECT 1 FROM nodeassignments WHERE assignmentid = a.id) \
                AND lower(n.name) = lower('%{User-Name}') \
            GROUP BY n.id \
        ) y ON (1=1) \
        RIGHT JOIN ( \
            SELECT n.id, n.name, 64 AS downceil, 64 AS upceil \
            FROM vnodes n WHERE lower(n.name) = lower('%{User-Name}') \
        ) z ON (1=1)"
}
